### ISSUE TITLE
Promote incrementProperty, decrementProperty, and toggleProperty to Ember namespace

### ISSUE THREAD

**Issue by kellyselden** [emberjs/rfcs#129]
Part consistency, part convenience. You can then use it functionally like its siblings. For example:

``` js
const {
  set,
  setProperties,
  toggleProperty // not possible currently
} = Ember;
```

I've started using this functional style in my code, and it would be nice not to have these exceptions that can't be destructured.

**Comment by mmun** [comment]
I'm a big fan. Additionally I'd like to see the array methods accessible this way too, so that addon authors can more easily support apps that choose to disable prototype extensions.

**Comment by locks** [comment]
I like the sentiment, but I thought the new module shims were moving away from the `Ember` module being a grab bag. Can we expose them as static functions from the relevant packages instead? Example:

    import { set, setProperties, toggleProperty }  from 'ember/object';
    import { find, reduce }  from 'ember/array';

**Comment by kellyselden** [comment]
@locks That works too.

**Comment by locks** [comment]
`set` and `setProperties` can be imported from `@ember/object`.
Do you think it's still relevant to add `toggleProperty`, especially in light of Octane?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue? My guess would be that incrementProperty and decrementProperty will eventually be deprecated.

By closing some old issues we reduce the list of open issues to a more manageable set.
