### ISSUE TITLE
Getting feedback on API changes for a popular addon

### ISSUE THREAD

**Issue by taras** [emberjs/rfcs#182]
@stefanpenner suggested that API changes in [`ember-ajax`](http://github.com/ember-cli/ember-ajax) should go through the RFC process. We, maintainers of ember-ajax, love this idea because it'll give the community an opportunity to provide feedback on API changes and give us information that we need to make `ember-ajax` better for everyone.

To help us move forward, we'd appreciate answers to the following questions:

1. Which *rfcs* repository should we use? (`[ember-cli/rfcs](https://github.com/ember-cli/rfcs), [emberjs/rfcs](https://github.com/emberjs/rfcs) or some other?)
2. How should we introduce breaking changes? 
3. Are there any resources or recommended way to version an addon that's included in the `ember-cli` app blueprint?

**Comment by workmanw** [comment]
I too really like the idea of popular addons going through RFCs, if for no other reason that to make it easy to have visibility into coming changes. And I don't think it should be exclusive to `ember-ajax` or any other addon that is an ember-cli default.

I'd kind of like to see a new repo, maybe `emberjs/addon-rfcs`, `ember-cli/addon-rfcs` or maybe a new ember organization. I kind of envision a repo that is generally open for RFCs relating to any addons in the ecosystem. That would make it very easy to just subscribe to. It's possible it could become noisy and a maintenance issue over time, or it might not. I've seen other addons try to conduct RFCs in their own repos and get lower attention, I suspect because many of us don't subscribe to all of the repos for the addons we use.

Anyways, just my $0.02.

**Comment by webark** [comment]
I think having it be for potentially ALL addons could get a little noisy, but for addons that are included by default by ember-cli, I think it would be very beneficial.

**Comment by martndemus** [comment]
> for addons that are included by default by ember-cli, I think it would be very beneficial.

Yes, though I think `ember-ajax` should be cut loose from the default blueprint. (AFAIK) This addon is not essential for an Ember app, and thus shouldn't be included by default, even though it is an addon from the Ember CLI org.

**Comment by taras** [comment]
@rwjblue @stefanpenner could you please provide some direction on this?

**Comment by XaserAcheron** [comment]
`ember-ajax` is kind of an odd case since one of its big (potential) goals is to [become the official backend for ember-data](https://github.com/emberjs/data/issues/4175), which would pretty much elevate it to "essential" status.

However, to make that goal a reality, `ember-ajax` needs quality RFCs, which in turn need several quality pairs of eyes on them, which means they'd best go in something "official" like `emberjs/rfcs` or `ember-cli/rfcs`... i.e. the best route toward making the addon more "official" is to treat it like it already is. Bit chicken-and-egg, kinda.

Having something like `ember-cli/addon-rfcs` for default-blueprint addons (including `ember-ajax`), as @workmanw and @webark suggested, sounds like a good compromise.

**Comment by averydev** [comment]
I like the idea of RFCs for this kind of add-on, because it will be easier to keep track of really important changes to the ecosystem in one place. Maybe we could just use an issue tag as is done with the `ember-data` tag in emberjs/rfcs. 

Not to over-use the RFC concept, but maybe to include an “addon” like ember-ajax an RFC could be opened regarding the inclusion of that add-on as RFC-able? The flow would look like this:

1. New RFC created to include add-on as RFC-able in the repo
1. RFC approved
1. Tag created for that addon (could be `addon-ember-ajax` for instance) 
1. Subsequent RFCs for that addon can be created and are tagged appropriately

**Comment by locks** [comment]
Thanks for the discussion! I'm closing as no longer relevant.
