### ISSUE TITLE
Feature request: Include {vendor/app}.{css.js} directly inside index.html 

### ISSUE THREAD

**Issue by ShogunPanda** [emberjs/rfcs#195]
Hi all!
As you know, in the index.html we have statements like:

<script src="{{rootURL}}assets/vendor.js"></script>
Now, I wonder if, when serving/building we can import the target script inline (so <script>...</script>) rather than pointing to an external file. This should speed up loading a little and also avoid the "above-the-fold" problem that Google PageSpeed Insights reports even without using FastBoot.

Thanks!

**Comment by nathanhammond** [comment]
@ShogunPanda Having a default story for "priority inlining" is something we would be interested in, but we can't make just a single decision as to what is the best for every site. Rather than trying to solve all of the problems ourselves we've built the ability to do this exploration in a distributed manner in the community: Ember CLI addons.

You can do additional processing in `postprocessTree('all')` to insert the contents into `index.html`. I'd encourage you to explore building an addon to accomplish this. It's unlikely that we will make this a default part of the Ember experience but you can build it into something like `ember-css-inliner` which can be added to applications via `ember install`. Be sure to report back here with what you come up with!

**Comment by ShogunPanda** [comment]
@nathanhammond 
That's incredible. It has been way less complicated than I expected to develop this (one day to do everything). Thanks for the hint! ^^

Let me introduce [ember-cli-all-in-one](https://www.npmjs.com/package/ember-cli-all-in-one).

Can you take a look and tell me what you think? I really appreciate it!
In the meanwhile, I'm closing this since it doesn't apply anymore.

See ya!
