### ISSUE TITLE
Feature suggestion: Percolate stack traces

### ISSUE THREAD

**Issue by locks** [emberjs/rfcs#249]
Originally by @rocifier at https://github.com/emberjs/ember.js/issues/15639.

> Ember stacktraces are hard to debug due to the asynchronous nature of javascript and the run loop. Could we do something like https://www.npmjs.com/package/async-stacktrace does and track the stack traces right through the loop, even if it's only on ember debug builds or something? This would make tracking the origin of exceptions much easier, as this is a large hurdle for newcomers.

**Comment by trentmwillis** [comment]
I'd be a big fan of this. I'm sure it is a non-trivial amount of work, but after seeing what the new React Fiber stacktraces look like, I think there is lots of room for improvement.

**Comment by NullVoxPopuli** [comment]
I made a demo of how an error that occurs in a modifier is pretty much worthless: https://codesandbox.io/s/modifier-error-stacktrace-test-zb5bl?file=/app/modifiers/throw-error.js

Like, you get the JS file where it comes from, but not the template. Since Ember is a template-focused framework, the template stack should be represented here as well.

**Comment by pzuraq** [comment]
This is something that I'd like to work on. I believe the original issue has been resolved for components themselves, we now have full stack traces for components, so errors that occur when rendering a component will have the stack trace.

The issue with modifiers is that they run _after_ rendering. So, the stack has already been unwound at that point. To improve this, we probably need to have an alternative way to thread that information through when the modifiers are first created.
