### ISSUE TITLE
Yield `href` to `link-to`s block

### ISSUE THREAD

**Issue by geoffreyd** [emberjs/rfcs#250]
I've had a number of times where I've needed to render a link, where the `innerText` needs to contain the `href`. When `link-to`ing a route, the href is dynamic, so I don't want to hardcode the value.

As a dev, I have a few options. 
1) Write a computed property that pulls in the router service and calculate what the path for a route is going to be given it's models. This requires some digging into router API's and creating extra logic that a normal link-to wouldn't need.

2) What I've started to do, create my own link-to component, that extends embers.

```
// components/link-to/component.js
import Ember from 'ember';
import layout from '../templates/link-to';

export default Ember.LinkComponent.extend({
  layout
});

// components/link-to/template.hbs
{{#if linkTitle}}
  {{linkTitle}}
{{else}}
  {{yield (hash href=(readonly href) ) }}
{{/if}}
```

An optional extension that we've implemented is to expose a `fullURL`, as this is often what we actually want. But I can understand this not wanting to be included, as it could be done with a simple helper, given a link's href.

```
// component.js
  fullURL: Ember.computed('href', function() {
    const href = this.get('href');

    if (href.startsWith('/')) {
      return `${window.location.origin}${href}`;
    } else {
      return href;
    }
  })

// template.hbs
{{#if linkTitle}}
  {{linkTitle}}
{{else}}
  {{yield (hash href=(readonly href) fullURL=fullURL)}}
{{/if}}
```

I'd like to propose including this yield into ember's link-to component.

Feedback on if this is interesting enough to write up an RFC would be appreciated.

**Comment by locks** [comment]
Hi @geoffreyd, I think this is a job for the Router service introduced in RFC 95, more specifically, [`urlFor` and a possible `url-for` helper](https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md#new-method-url-generation).
We have implemented and make public phase 1 of the implementation of that RFC in Ember v2.15. There should be a public roadmap very soon with the following phases laid out, so you can follow along.

**Comment by jcope2013** [comment]
there is a url-for helper that uses the new routing service in this repo https://github.com/rwjblue/ember-router-helpers

**Comment by geoffreyd** [comment]
Thanks,

So using that proposed/add-on `url-for` helper, I could achieve the same with the following?

```
{{#link-to 'article' article}}
Visit: {{url-for 'article' article}}
{{/link-to}}
```

This it nice, but also unnecessarily verbose, considering that `link-to` already knows this information.

**Comment by nathanhammond** [comment]
@geoffreyd Note that `link-to` does a whole bunch of work and is something that a number of us wish to speed up (or even avoid completely: https://github.com/intercom/ember-href-to). It requires and parses the destination route and controller, handles active states, and more. Adding in additional complexity is not something that *I* really want to do for such an integral component of Ember, no matter how seemingly trivial. I suspect that many others feel the same way.

However, you've already noticed that Ember's `link-to` is a component (it used to be a `keyword` which prevented extension), and what you've described above (where you re-extend the component) is exactly our intended escape path if you need additional behavior.

It has become (intentionally) increasingly difficult to make changes to core parts of Ember APIs. The bar is higher because of our desire to limit size, stabilize APIs, and limit the learning curve. For something that has has been in the library for now six years without tremendous changes the bar for inclusion must be set accordingly high. (Also, this is the first time I've seen this request in that time period implying low frequency of need.)

Given the escape path, implied low frequency of need, and where I understand the bar for inclusion to be on a feature change to `link-to` I'm opposed to this change.

**Comment by geoffreyd** [comment]
@nathanhammond Thanks for that great reply. 

That extra work you mentioned `link-to` doing, is what I was wanting to avoid, by calling 
```
{{#link-to 'article' article}}
  {{url-for 'article' article}}
{{/link-to}}
```
As I assume `url-for` would also have to do that work? So why not just use the work that `link-to` has already done.

They way that I've implemented it, the usage looks like:

```
{{#link-to 'articles' as |link|}}
  {{link.href}}
{{/link-to}}
```

So it is a purely additive change, and a great use of one of ember's strengths. It doesn't effect any exisiting usages.

Saying that, I agree with your point that it is easy enough to extend `link-to`, as I've done, and if you've not seen this use case before, it's probably not worth the change.

**Comment by nathanhammond** [comment]
Edited my previous message to strike the "breaking API change" comment. I didn't think that through (and added it as an edit to the original comment, "oh, also this!"). Thanks for correcting me. 😄

**Comment by rtablada** [comment]
@geoffreyd I think saying that `link-to` and `url-for` are doing the same heavy lifting twice in my mind is a better argument for memoization or caching of `urlFor` results rather than this API change. 

Not sure how that would fit in the scope of reducing API complexity as @nathanhammond mentioned, but could be worth investigating in the future or even a separate RFC.
