### ISSUE TITLE
Local Storage Support in Ember Data

### ISSUE THREAD

**Issue by ghost** [emberjs/rfcs#256]
I found this post from 2012 http://hawkins.io/2012/07/ember_wish_list/.

Since then something is changed, but not this point:

**Low Hanging Fruit - Local Storage Support in Ember Data**
Loading screens blow. I downloaded the data. I shouldn't have to keep going to the server to get it again. You are probably using HTTP caching, but that still creates network requests. Getting good performance means cutting down on network requests. It's not very complicated to do in Backbone. Ember data should support local storage by default. For example, you create your store and you can set storedLocally: false if you don't want it stored. I think that adding local storage to support to the framework and enabling it by default would be a major win. Our app is dealing with a lot of data. Loading in data takes time and reduces performance. We only want to download that data once.

All points here: https://github.com/emberjs/rfcs/issues/254

**Comment by mkay581** [comment]
Every team implementing an ember app is not going to always want data stored on the client, for security reasons, etc. Can't this just be an Ember addon that simply extends [DS.Store](https://www.emberjs.com/api/ember-data/2.14/classes/DS.Store), he store that ships with Ember?

Also, I believe doing `query()`s causes new server requests to be made each time, but using methods like `findAll()`, `findRecord()`, etc don't make new requests but instead return cached versions from the store.

**Comment by locks** [comment]
@mkay581 I believe that OP means [Window.localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). The data in `localStorage` gets persisted in the browser until you clear it.
Ember Data's store is a JavaScript in-memory cache that gets wiped with the rest of the JavaScript as soon as you close the browser tab.

**Comment by mkay581** [comment]
Yeah. I guess I'm wondering why impose local storage on all ember-data backed applications by default? It seems that this is a rather large task for what seems like a rare use case, which may be more beneficial if it were implemented into an addon.

Local storage data persists in the browser (pretty much forever) until it's cleared, so it can become stale (out of date). Also, I think that most Ember developers would be concerned with the security of this data being stored locally rather than in secure database accessible via an https protocol by a sanitized server. In cases where the user logs into Ember app and needs to be authenticated, dealing with authenticating data in local storage doesn't seem like a small task.

**Comment by locks** [comment]
There are currently several attempts at both a local storage addon for Ember Data, as well as Ember Data alternatives like Orbit.js. Thanks for bringing it up and for the discussion!
