### ISSUE TITLE
Have a function to "Leave" a route.

### ISSUE THREAD

**Issue by Benjy1979** [emberjs/rfcs#342]
Put a leave() function on a route, that jumps to the immediate parent route.

This is so that it is not necessary to have to specify the full path of the route in transitionTo(), from a child route to a parent route. It also guarantees that you do not have to respecify arguments to the parent routes (which means having to obtain/track them down), because they will stay the same if you are using "leave()" which simply jumps to the parent route keeping everything the same.

It's better for reusing route code from application to application.

**Comment by knownasilya** [comment]
At one point i thought that if you are going up a child, you didn't need to specify the arguments for `transitionTo`/`link-to` and that it would just know what they are, since the system already has them. I'm still fixing bugs to this day from that assumption :neckbeard:

**Comment by locks** [comment]
I believe a POC can be implemented as an addon. I would not name it `leave()`, as what you are doing is navigating up one level of the route hierarchy.
What happens when you are in `a.index`, or `application`?

**Comment by knownasilya** [comment]
Maybe `backToRoute`. The index route would send back to its parent or to its parent's parent, probably based on an option.

**Comment by knownasilya** [comment]
Good point.

**Comment by Benjy1979** [comment]
Or Leave({ ignoreIndex: true})?

I find when a show an overlay on a child route, then closing the overlay goes back to the parent. It's a chore to have to specify the route you're going back to. Especially if you have used a component which is supposed to be reusable and context neutral.

**Comment by mehulkar** [comment]
Hah, this lines up nicely with something I'm working on right now--good timing. This would be a great API: `router.transitionTo(router.currentRoute.parent)`

The primitive here here, is that `transitionTo` accepts a `RouteInfo` object. (I also see a `RouteInfoWithAttributes` object, btw, but I'm not sure if that's relevant here since going from a leaf route up to a parent should not need a reference to the resolved model).

**Comment by Benjy1979** [comment]
I was going to add another feature request but I think it ties into the same need here.
How about being able to use a RouteInfo to transition with? IE you could pull off transition.from() and route back to where you came from with all the same parameters, this could include what I initially suggested by leaving to the parent - it should include all parameters.

The thing that makes routes unwieldy sometimes is the need to keep plugging the parameters back in. Being able to transitionTo with the RouteInfo object (or something else, contained) would make tracking through routes (ie states of the application) a dream.

**Comment by rwjblue** [comment]
I think we could write a utility function that does that, not 100% that it belongs in core (vs an addon) but I do think it would be really nice to have.

**Comment by locks** [comment]
We now have the router service with `routeWillChange` and `routeDidChange` events, which might be useful for implementing the thing discussed above.
Since there hasn't been further discussion, I'd recommend giving it a go implmenting something with the `RouterService`, and then see the missing pieces.
