### ISSUE TITLE
Subclass Components should inherit superclass' layout by default

### ISSUE THREAD

**Issue by gabrielgrant** [emberjs/rfcs#412]
I see a few suggestions that an component that inherits from a parent component should also adopt it's parent's template if a template for the child is not defined

eg [Stack Overflow Answer 1](http://stackoverflow.com/a/42484551/260491), [Stack Overflow Answer 2](http://stackoverflow.com/a/32148278/260491) and  [this GH comment](https://github.com/emberjs/ember.js/issues/12467#issuecomment-182975133) by @rwjblue ("if a template is resolved for a given component's layout it will always override whatever layout property you define") seems to imply that if _no_ template is resolved, an inherited component's `layout` property should be used (thus rendering the parent template for the child).

But this isn't the behavior i'm seeing: inheriting from a parent component results in an empty child, unless the child's `layout` property is set explicitly. (thanks @locks for helping me figure this out in slack)

See this Twiddle for an example:
https://ember-twiddle.com/5ce231363b6cc92127b0f99f59734c9b?openFiles=templates.application.hbs%2Ctemplates.components.parent-component.hbs

While annoying, this isn't entirely unreasonable for a single level of inheritance, but really feels broken when adding a grandchild to the inheritance chain: it has to know it's extending a subclass, and explicitly import the template for it's parent parent.

It seems like it'd be pretty reasonable to inherit a parent's template if one isn't defined for the child. If someone *really* wanted an empty template, creating an empty template file explicitly would achieve it.

**Comment by rwjblue** [comment]
FYI - I just transferred this issue over from emberjs/ember.js to emberjs/rfcs because this neccesarily requires new public APIs to implement as originally suggested. There are two RFCs in the works that this may apply to (glimmer component RFC and "template imports" RFC), so it seemed good to have this over in the same repo...

**Comment by gabrielgrant** [comment]
@rwjblue I take that to be a confirmation that the current behavior is considered correct, and any change would be a change in design? (as per https://github.com/emberjs/rfcs/issues/412#issuecomment-297489996 )

**Comment by rwjblue** [comment]
“Correct” is a bit strong here, but yes. The current behavior at least isn’t _a bug_, but it definitely doesn’t seem great and an RFC to attempt to fix it seems good IMHO.

**Comment by DLiblik** [comment]
I was about to ask how to delegate to the parent template on ES6 component classes... then I thought to myself "Self - try deleting the template for the child and see what happens..." and it worked (I'm using pods just in case that matters...)! 👍  

Posting this here because I spent some solid time on trying variations of overriding `layout` to no avail and ended up on this thread -- might help others.

**Comment by rwjblue** [comment]
FWIW, colocated templates are inherited automatically.

**Comment by mehulkar** [comment]
ping @locks for closing this maybe?

**Comment by locks** [comment]
Closing! Thanks for the discussion everyone :)
