### ISSUE TITLE
[ember-cli] Public API to examine app dependencies from an addon

### ISSUE THREAD

**Issue by jrjohnson** [emberjs/rfcs#436]
In an addon I can look in `project.packageInfoCache.entries` and see all of the installed packages at app build time, but as @Turbo87 mentions in https://github.com/ivanvanderbyl/ember-d3/pull/69#pullrequestreview-194349135 this doesn't appear to be public. 

In addons like `ember-d3` or `@fortawesome/ember-fontawesome` where it is important to validate or transform packages at build time this is needed functionality.

The private method https://ember-cli.com/api/classes/Project.html#method_dependencies exposes this, but only at the level of the application not the deep tree present in `project.packageInfoCache.entries`.

**Comment by ef4** [comment]
This is an old issue and I'm going to close it. The suggestion made sense back when it was filed. It doesn't really align with how we see the build working in modern Ember, because addons doing dynamic things to inspect and manipulate the build leads to a morass of lock-in and un-optimizable behaviors.
