### ISSUE TITLE
Pre RFC/Feature Request: New builtin helper: compose

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/rfcs#546]
Initial "Discussion": https://discordapp.com/channels/480462759797063690/488717827323461632/626794075454046248

This is in an effort to address some the issues described here: https://github.com/emberjs/rfcs/issues/497

Mainly that, we don't have a way to assign/differentiate between args and attributes using the existing `component` helper.

A few people have tried to `{{yield (component 'component-name' ...attributes)}}` which errors, because:
 1. splat in a helper isn't supported afaik
 2. no way to tell if the attributes are not args from within the component helper

So, in response to that, I'd like to propose a new helper: `compose`, demonstrated below (also using component imports):

```ts
import Component from '@glimmer/component';
import { setComponentTemplate } from '@ember/component';

import Foo from 'my-app/components/foo';

class WhateverComponent extends Component {}

export default setComponentTemplate(hbs`
  {{yield (hash
    Foo=(compose Foo 
      args=(hash ...) 
      attributes=(hash a=1 ...attributes)
    ) 
  )}}
`, WhateverComponent);
```

```hbs
<WhateverComponent class='foo' as |stuff|>
  <stuff.Foo a=2/> 
</WhateverComponent>
```

This'd be the same as this today:
```hbs
<stuff.Foo a=2  ...attributes class='foo' /> 
```

So, why `compose`?

when yielding a component, it does not feel like you are invoking the same component when in the calling context, or at least not without a wrapper function. I've been thinking of it like this (assuming this made up version of JS shorthand):

`const Foo = (...args) => console.log('foo', ...args);`

yield => { Foo: () => Foo(args I want to pass when invoked from the calling context) }

To me, it feels like yielding contextual helpers makes super lightweight closures around our components -- we're _composing_ new anonymous components in a way. (I have no idea if that's how it works underneath, or if it's just some arguments merging)

**Comment by chriskrycho** [comment]
I think something in this space is a good idea. A couple notes, though:

First: I think `compose` is the wrong term here. Function composition is well-defined, and this isn't that.

```ts
function compose(g: (b: B) => C, f, (a: A) => B)): (a: A) => C {
}
```

Second, Making a more direct way to pass a component invocation inline might be better?

**Comment by pzuraq** [comment]
I think a design like this relies heavily on:

1. How `...` style spread syntax would work in helpers/nested helpers. Currently, this doesn't exist yet, there's been discussion of having a general spread syntax (e.g. following splarguments), but it hasn't been nailed down
2. How `attributes` can be accessed in general inside helpers. Currently, I don't believe it can - it's a keyword specifically _outside_ of helpers, which was very intentional.

I think that in order to ship something like this we need to make some calls about these two things, especially spreading. If we want to be able to spread any value in nested helpers, we need to make sure that design doesn't foreclose on the ability to spread in _general_. Exposing attributes is a bit of a different matter, I'm less concerned about it but I'm sure there are some reasons we'd want to be cautious before we do that.

**Comment by rwjblue** [comment]
I'm pretty opposed to claiming a vague high level name for this functionality (`compose`). I'd much prefer a design that would give context when reviewing. For example, consider a keyword named `with-attributes` it is clear what it does (adds attributes) and doesn't claim a common english word as reserved.

Usage could look like:

```hbs
{{yield 
  (with-attributes 
    (component "my-component" some-arg=whatever)
    class="foo" data-whatever-attribute="bar" (modifier 'on' 'click' this.blah)
  )
}}
```

**Comment by rwjblue** [comment]
Also, I don't grok why we need a separate issue to discuss this. Any reason not to close and continue discussion in https://github.com/emberjs/rfcs/issues/497?

**Comment by NullVoxPopuli** [comment]
I think with-attributes is growing on me :)
