### ISSUE TITLE
To include ember-template-inspector in ember-inspector

### ISSUE THREAD

**Issue by siva-sundar** [emberjs/rfcs#703]
Hi,

https://github.com/siva-sundar/ember-template-inspector#ember-template-inspector

This add-on opens the template file in the code editor while inspecting an element. Would it be better if we include it in the ember-inspector ?

This reduces the time to debug things.

Kindly share your thoughts.

**Comment by siva-sundar** [comment]
Currently this adds the file location(along with line and column) to the html element as an attribute as `l=1:2:14:30`. 

If there is a way to include meta info to html tags, we can avoid the attributes.

**Comment by sandstrom** [comment]
Does it require a plugin/extension in the browser too? Or does it jack into the existing ember-inspector addon?

Or is it a regular click-handler, that works with any browser?

**Comment by buschtoens** [comment]
From a quick glance at the source code, it seems that this addon only supports classic `@ember/component`. Does it support `@glimmer/component` as well?

If we were to include this in the default blueprint, I'd make `@glimmer/component` a requirement.

**Comment by siva-sundar** [comment]
> Interesting idea!
> 
> Does it require a plugin/extension in the browser too? Or does it jack into the existing ember-inspector addon?
> 
> Or is it a regular click-handler, that works with any browser?

It works on any browser and it doesn't require ember inspector as well. As you mentioned, it works using click handler.

**Comment by siva-sundar** [comment]
> From a quick glance at the source code, it seems that this addon only supports classic @ember/component. Does it support @glimmer/component as well?

This add-on works by adding the location to the html element. It covers both `@glimmer/component` and `@ember/component` templates.

**Comment by sandstrom** [comment]
A few thoughts:

### Click handlers

One downside with using a regular click handler + adding this as a default for new apps is that click handlers can interfere with regular app functionality.

As long as it's an addon that people can choose to include, that's less of a problem. But I think that would be a big problem for something added by default. Also, I think it would need to garner more usage before it would qualify as a default addon.

If one wanted to avoid using regular click handlers, it would probably need to be wired into ember-inspector, via e.g. html attributes. 

### Ember Inspector
Since ember inspector already has a feature for identifying components, maybe it would be better if this was somehow made to work with ember inspector, or built as a feature for ember inspector?

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/122287/104560568-5a713480-5646-11eb-8fac-dee506872208.png">

**Comment by siva-sundar** [comment]
@sandstrom I agree. Providing the functionality in ember-inspector is the right option. For the time-being, I developed this as an add-on. Even React provides this option in its inspector.

As mentioned earlier, this add-on enables you inspector the HTML elements. So, I feel we need to introduce a separate action(or tab) for opening files.

**Comment by sandstrom** [comment]
I guess it could also be a separate link *after* the component is opened. So basically on the top row next to "ActiveLinkComponent" there could be a link to "open in your editor".

**Comment by jelhan** [comment]
Maybe even the Ember Inspector could show the template of the component directly? Maybe it could even show the current value of a property / argument when hovering over it in the template? :exploding_head:

**Comment by siva-sundar** [comment]
> I guess it could also be a separate link after the component is opened. So basically on the top row next to "ActiveLinkComponent" there could be a link to "open in your editor".

While hovering we can't do other actions like opening the file. For additional actions, we need to define a separate one.

**Comment by mehulkar** [comment]
I think this is a great addon, but I would not want it to be in the default blueprint. I would like to see package.json grow _smaller_ over time and this is a Nice to Have feature. I would even use it sometimes, but I would not want it to be part of my project.

**Comment by siva-sundar** [comment]
Closing this issue.
