### ISSUE TITLE
Short hand if helper: `?` (or other symbol helpers)

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/rfcs#768]
What are folks initial thoughts on having a short-hand if helper:

`?`

example:

```hbs
{{? condition 'truthy value' 'falsey value'}}
```

Maybe these are just aliases:
`?` === `if`
`!` === 'not'
':` === 'or'
'&' === 'and'

```hbs
{{? condition 'truthy'}}
{{? (! condition) 'negated truthy'}}
{{? (& conditionA conditionB) 'anded truthy'}}
{{? (: conditionA conditionB) 'ored truthy'}}
```

Idk if this is silly, since it's saving so few characters, but developers are lazy, and like to save on typing, so I wanted to get a discussion going.

**Comment by chriskrycho** [comment]
I'd be strongly opposed. It's not at all search-able, and is easy to overlook. Brevity by way of sigils is a good way to end up illegible.

---

If we want to save on typing and improve the ergonomics of things like `if`, we'd be better off looking at what it would take to implement a "Sveltebars" syntax, with single curlies, a JS/C-like function invocation order, etc.—potentially even supporting the same kind of small expression subset of JS as Svelte. The only really significant differences between Svelte's *templates* and ours are named arguments and the expanded subset of JS expressions Svelte allows, specifically callback syntax.

- the syntax for directives vs. modifiers is purely syntactical: `<element use:someDirective={valueInScope}>` vs. `<element {{someDirective valueInScope}}>`
- our inline `if` has the same semantics with regard to values in scope as a ternary (with implicit `: undefined` for the single case)
- block `if` and `each` are effectively identical
- `{{value}}` vs. `{value}` is just ("just", of course) a parse difference

Named args don't parse with Svelte's parser now, but should be able to be added straightforwardly. Callback syntax is the one thing we don't have a clean analog to, because we have no support for native object or array syntax, much less destructuring, and we don't have syntax for defining a helper directly inline in a template – even with template imports it has to be in a separate language context, even if it's trivial and makes perfect sense "inline".

**Comment by NullVoxPopuli** [comment]
Most excellent -- we've now discussed it. :D
