### ISSUE TITLE
Enable using `npx ember`

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfcs#780]
`npx ember` does not work even though we use `ember` as the main command to generate projects and within projects. 

Seeking comment on the idea of adding a bin to the `ember` npm package to enable `npx ember`. This would primarily be useful in cases where you currently want to use `npx ember-cli`. I personally do this primarily when generating new projects. It would provide a convenience for those of us who easily forget that `npx ember` does not work.

**Comment by jelhan** [comment]
I see that it would help with teaching. We wouldn't need to teach `ember-cli` package before even creating an Ember application. But I fear complexity grows a lot as soon as we try to define what it actually does. Some questions, which came to my mind:

- What would that bin do? I guess it would execute `npx ember-cli`?
- Which version of `ember-cli` would it use if one is provided explicitly? `ember` and `ember-cli` packages are released independently. Actually [`ember` package](https://www.npmjs.com/package/ember) has not been released since four years. Wouldn't it be very confusing if `npx ember@3.28.0` does not work?

Maybe `npx ember` could only log a message pointing to `npx embrr-cli`?

**Comment by wagenet** [comment]
This is an interesting idea, but it doesn't seem like there's a push to move this forward. I'm going to close for now but if someone wants to get the ball rolling again, let me know and I can reopen.

**Comment by NullVoxPopuli** [comment]
I volunteer
![I volunteer as tribute (from The Hunger Games)](https://media.tenor.com/b3H66uAAKwgAAAAC/i-volunteer-as-tribute-pick-me.gif)

**Comment by MichalBryxi** [comment]
Should this issue be re-opened then since we have a ... volunteer? :)
