### ISSUE TITLE
Public API support disparity with Glint and typed templates with custom managers -- currently no story for TS support (for now?)

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/rfcs#822]
Today, support for helpers, components, modifiers, etc is all hard-coded in Glint.

For folks wanting to use glint, and have their custom-manager implementations support TS, there is no path here.

I think we should figure out a path for managers to provide the types to Glint, based on the type of thing received in the template -- since
aside from raw-values, everything involves a manger -- components, helpers, modifiers, etc.

For example, 
 all of these use custom managers and have no way to utilize typed templates (would currently show unresolveable errors to consumers of these addons):
   - using the component manager
     - https://github.com/NullVoxPopuli/ember-statechart-component/
     - https://github.com/NullVoxPopuli/ember-lifecycle-component
     - https://github.com/NullVoxPopuli/ember-function-component
     - https://github.com/rwjblue/ember-functional-component
     - https://github.com/alexlafroscia/ember-context
     - https://github.com/izelnakri/glimmer-embedded
     - https://github.com/sandydoo/ember-google-maps
     - https://github.com/mjanjic01/ember-konva
       
   - using the helper manager
     - https://github.com/NullVoxPopuli/ember-functions-as-helper-polyfill/
     - https://github.com/nullvoxpopuli/ember-resources
     - https://github.com/BBVAEngineering/ember-route-helpers
     - https://github.com/tracked-tools/ember-could-get-used-to-this
     - https://github.com/LevelbossMike/ember-statecharts
     - https://github.com/izelnakri/emberx
     - https://github.com/josemarluedke/glimmer-apollo
   
   - using the modifier manager
     - https://github.com/NullVoxPopuli/ember-functions-as-modifiers-polyfill/
     - https://github.com/pgengler/flashcards-client
     - https://github.com/gmurphey/ember-did-resize-modifier
     - https://github.com/hashicorp/consul
     - https://github.com/wongpeiyi/ember-animated-routes
     - https://github.com/chadian/ember-fill-up
     - https://github.com/OAGAnalytics/ember-split-view-modifier
     - https://github.com/tracked-tools/ember-could-get-used-to-this
     - https://github.com/NullVoxPopuli/ember-popperjs
     - https://github.com/lifeart/ember-ref-modifier
     - https://github.com/josemarluedke/ember-focus-trap
     - https://github.com/upfluence/oss-components
   
   - what do we do if we add more managers? (like a service manager)
   
(as a disclaimer, I used github's search, and picked out a few things -- idk how used these things are -- but it looks like many are used by sizable companies)   
   
   
Atm, `@glimmer/component`, specifically has `ExpandSignature`: https://github.com/typed-ember/glint/blob/0e31e49301776d552429892d5749ecbf88f68d00/packages/template/-private/index.d.ts
   
RFC here: https://github.com/emberjs/rfcs/pull/748
   
So (atm), I'm kinda thinking we need some sort of "ExpandSignature" type thing per syntax, rather than per implementation.
So, right now we have a `ExpandSignature` for the glimmer/component -- but what about all the other components? Or how does Expanding the signature of a helper or modifier work? we know what these are statically as they're all matched on prototype, so I can imagine "something" like:

```ts
interface HelperManagerLookup {
  [SomeHelperPrototype]: SignaturueForThisHelper,
  [EmberHelperProtoype]: EmberHelperSignature,
}
```
(and similar for modifiers, components, and maybe eventually services, too? idk)
   
   
   
Relevant discussion in Discord: https://discord.com/channels/480462759797063690/814921339219476571/980229057931276308

**Comment by dfreeman** [comment]
Ok there's a lot to cover here, so I'm going to take it in order.

> For folks wanting to use glint, and have their custom-manager implementations support TS, there is no path here.

Glint was designed from the ground up to support this; the entire poing of the `@glint/environment-*` packages is to provide bindings between Glint's notion of how template types work and arbitrary implementations of components/helpers/modifiers. Those packages aren't privileged in any way, though, and the core doesn't have special knowledge of them—that's how we were able to prototype `glint-environment-ember-template-imports` in a standalone library before incorporating it into the monorepo.

> I think we should figure out a path for managers to provide the types to Glint,

Managers turn out to be a red herring for providing types to Glint, as the TS type system has no way of modeling "a value that has had this function called on it". We explored approaches to making that work early on, but ultimately it also turns out it's just not very useful: the manager doesn't really give us the full information at a type level to understand how the thing it acts on is going to work in a template anyway.

> all of these use custom managers and have no way to utilize typed templates

Have you checked Glint's issue tracker? We've had conversations about how to do this 🙂 

> Atm, @glimmer/component, specifically has ExpandSignature: [typed-ember/glint@0e31e49/packages/template/-private/index.d.ts](https://github.com/typed-ember/glint/blob/0e31e49301776d552429892d5749ecbf88f68d00/packages/template/-private/index.d.ts)
> RFC here: https://github.com/emberjs/rfcs/pull/748
> So (atm), I'm kinda thinking we need some sort of "ExpandSignature" type thing per syntax, rather than per implementation.

I think you've misunderstood what `ExpandSignature` is. It doesn't actually have anything to do with making Glint work—it is just about, well, "expanding a signature" from its shorthand form to the full longhand one as specified in the RFC you linked. The reason there's no helper or modifier equivalent is that there _is no shorthand_ for `@ember/component/helper` or `ember-modifier` signatures. Other base component/helper/modifier implementations can use any structure they like to capture the relevant type information, as long as the key pieces are there somewhere (more on that below).

> what if library authors provided a way for certain constructs to tie in to Glint in strict mode?

It's not specific to strict mode, but you're slowly working your way toward reinventing how Glint already works 😉 

I'm not super familiar with the shape of the resource base class, but you should be able to write something along these lines to make Glint aware of how `Resource` subclasses behave in templates:

```ts
interface Resource<T extends ArgsWrapper> extends InstanceType<
  HelperLike<{
    Args: { Named: T['named']; Positional: T['positional'] };
    Return: IDontKnowHowToGetTheValueTypeOfAResourceButItGoesHere
  }>
> {}
```

This is exactly how we integrate Ember's own base classes into Glint (for example, here's [`Helper`](https://github.com/typed-ember/glint/blob/b4fea147cda54339d1b2f87cee3c4709c277eab3/packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts#L59)).

**Comment by wagenet** [comment]
It sounds like @dfreeman is saying that the issues @NullVoxPopuli identified already have solutions. Is this a correct understanding? Is there any path forward for this ticket?

**Comment by NullVoxPopuli** [comment]
Sort of, we have my specific issue solved by extending upstream / third-party types like here: https://github.com/NullVoxPopuli/ember-statechart-component/blob/main/ember-statechart-component/src/glint.ts#L39

I can't speak for the typed-ember folks, but if this is the path forward for all situations like this, I'm happy with closing this

**Comment by dfreeman** [comment]
Extending upstream types is the name of the game—it's how pretty much all of Glint works 🙂
